services:
  app:
    image: mysociety/mp-quiz:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/mp_quiz      
    volumes:
      - ./:/workspaces/mp_quiz/