theme: jekyll-theme-slate
title: "MP Name Quiz"
description: "Say goodbye to the 2019-2024 Parliament by naming as many as you can."

baseurl: "/mp-quiz"
url: "https://pages.mysociety.org"

navigation:
  - title: "Donate £10 to mySociety"
    url: "https://www.theyworkforyou.com/support-us/?utm_source=mp-quiz&utm_medium=referral&utm_campaign=mp-quiz&how-much=10&how-often=one-off#donate-form"

collections:
  versionlists:
    output: true
  datasets:
    output: true
  downloads:
    output: true
  analysis:
    output: true


defaults:
  - scope:
      path: ""
      type: analysis
    values:
      layout: datasets/analysis
      external_css:
        - https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css
      external_js:
        - https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js
  - scope:
      path: ""
      type: versionlists
    values:
      layout: datasets/versions
  - scope:
      path: ""
      type: datasets
    values:
      layout: datasets/dataset
  - scope:
      path: ""
      type: downloads
    values:
      download_gate_type: soft
      download_form_header: Can you help us with funding by telling us more about yourself?
      download_survey: 6876792/Data-usage
      layout: datasets/download
plugins:
  - jekyll-feed

# Twitter
twittercard:
  enabled: true
  username: "@mysociety"

logo: "/img/social.png"
layouts_dir: theme/_layouts
includes_dir: theme/_includes

sass:
    sass_dir: 
    load_paths:
        - theme/sass
        - sass  


# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md